---
title: "comparison_results"
author: "Laura Menicacci"
date: "2023-12-13"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

# devtools::install_github("moritzpschwarz/getspanel")
library(tidyverse)
library(gets)
library(getspanel)
library(here)
library(doParallel)
library(readxl)
library(gdata)
library(devtools)
library(cowplot)


```



## Put all results together

```{r}

ccmt_IIS <- readRDS(".\\results\\ccmt_IIS.RDS")
ccmt_noIIS <- readRDS(".\\results\\ccmt_noIIS.RDS")
ccmt <- rbind(ccmt_IIS, ccmt_noIIS)

energy_IIS <- readRDS(".\\results\\energy_IIS.RDS")
energy_noIIS <- readRDS(".\\results\\energy_noIIS.RDS")
energy <- rbind(energy_IIS, energy_noIIS)

solar_IIS <- readRDS(".\\results\\solar_IIS.RDS")
solar_noIIS <- readRDS(".\\results\\solar_noIIS.RDS")
solar <- rbind(solar_IIS, solar_noIIS)

wind_IIS <- readRDS(".\\results\\wind_IIS.RDS")
wind_noIIS <- readRDS(".\\results\\wind_noIIS.RDS")
wind <- rbind(wind_IIS, wind_noIIS)

batteries_IIS <- readRDS(".\\results\\batteries_IIS.RDS")
batteries_noIIS <- readRDS(".\\results\\batteries_noIIS.RDS")
batteries <- rbind(batteries_IIS, batteries_noIIS)

```

## This function assigns a list of all the detected breaks for each model specification
```{r}

find_breaks <- function(results_df) {

  results_df$breaks <- vector("list", length = nrow(results_df))

  for (i  in 1:nrow(results_df)){
  
    for (j in results_df$is[i]) {
      
      for (k in j$isatpanel.result$ISnames) {
          breaks <- get_indicators(j)$fesis$name
          results_df$breaks[i] <- list(breaks)
    }
  }
  
}
 return(results_df)
  } 


# TO DO: MAKE MORE EFFICIENT (remove nested loops)


```

## more efficient function (non funge)

```{r}
find_breaks2 <- function(results_df) {
  results_df$breaks <- lapply(results_df$is, function(j) {
    lapply(j$isatpanel.result$ISnames, function(k) {
      get_indicators(j)$fesis$name
    })
  })
  return(results_df)
}


```



## add breaks

```{r}
ccmt <- find_breaks(ccmt) %>% mutate(tech = "ccmt")
 
energy <- find_breaks(energy) %>% mutate(tech = "energy")

solar <- find_breaks(solar) %>% mutate(tech = "solar")

wind <- find_breaks(wind) %>% mutate(tech = "wind")

batteries <- find_breaks(batteries) %>% mutate(tech = "batteries")

all_res <- rbind(ccmt, energy, solar, wind, batteries) 

saveRDS(all_res, ".\\all_res_break_comp.RDS")

```


## How to compare across models and samples the breaks? 

```{r}

df_long <- all_res %>%
  select(source, year_range, p_val, iis, ar, breaks) %>% 
  pivot_longer(cols = starts_with("breaks"), names_to = "index", values_to = "breaks")

# Find common elements across all lists
common_elements <- df_long %>%
  group_by(breaks) %>%
  filter(n() == nrow(df_long)) %>%
  ungroup()


element_counts <- count(common_elements, breaks)



```


## To answer: ccmt/energy vs specific techs, how many breaks in common?

