---
title: "Untitled"
author: "Laura Menicacci"
date: "2023-02-17"
output: html_document
---

# UNFCCC check things for publication


```{r setup, include=FALSE}
library(tidyverse)
library(countrycode)

unfccc <- read_csv("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/policy_databases/unfccc_final.csv")
```

```{r}

for (i in unfccc$`Policy Name`){grepl("\n", i)}

```


```{r}

for (i in unfccc$`Policy Description`){str_replace(i, "\\n", " ")}


```
# OECD missing transport and building policies


```{r}
library(readr)
library(countrycode)
ceres <- read_csv("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/ceres_versions/ceres_thirdversion.csv")
```

## Buildings - IEA

```{r}

IEA <- read_csv("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/policy_databases/policies_database_IEA_comma_utf8.csv")

iea_building <- IEA %>% 
  mutate(country_code = countrycode(Country, origin = "country.name", destination = "iso3c")) %>%
  filter(grepl(c("Buildings|Residential|building"), Sectors)) %>% 
  filter(grepl(c("Payment|finance and taxation"), `Policy types`, ignore.case = T)) %>% 
  filter(Year >= 2000 & Year <= 2020) %>% 
  filter(country_code %in% c("ARG","AUS","AUT","BEL","BGR","BRA","CAN","CHE","CHL","CHN","COL","CRI","CZE","DEU","DNK","ESP","EST","EUR","FIN","FRA","GBR","GRC","HRV","HUN","IDN","IND","IRL","ISL","ISR","ITA","JPN","KOR","LTU","LUX","LVA","MEX","MLT","NLD","NOR","PER","POL","PRT","ROU","RUS","SAU","SVK","SVN","SWE","TUR","USA","ZAF"))


iea_building_renovation_d <- iea_building %>% 
  filter(grepl(c("renovation|Renovation"), Description))

iea_building_renovation_p <- iea_building %>% 
  filter(grepl(c("renovation|Renovation"), Policy))

iea_building_renovation <- rbind(iea_building_renovation_d, iea_building_renovation_p) %>% distinct(.keep_all = TRUE)

write_csv(iea_building_renovation, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/IEA_building_renovation.csv")
  

```

## Transport - IEA

```{r}

IEA <- read_csv("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/policy_databases/policies_database_IEA_comma_utf8.csv")

iea_transport <- IEA %>% 
  mutate(country_code = countrycode(Country, origin = "country.name", destination = "iso3c")) %>%
  filter(grepl(c("Transport", "Road transport", "Passenger transport (Road)", "transport"), Sectors)) %>% 
  filter(grepl(c("Payment|finance and taxation"), `Policy types`, ignore.case = T)) %>% 
  filter(Year >= 2000 & Year <= 2020) %>% 
  filter(country_code %in% c("ARG","AUS","AUT","BEL","BGR","BRA","CAN","CHE","CHL","CHN","COL","CRI","CZE","DEU","DNK","ESP","EST","EUR","FIN","FRA","GBR","GRC","HRV","HUN","IDN","IND","IRL","ISL","ISR","ITA","JPN","KOR","LTU","LUX","LVA","MEX","MLT","NLD","NOR","PER","POL","PRT","ROU","RUS","SAU","SVK","SVN","SWE","TUR","USA","ZAF"))

################

scrappage <- c("scrappage|scrapping|Scrappage")
iea_transport_scrappage_d <- iea_transport %>% 
  filter(grepl(scrappage, Description, ignore.case = T))

iea_transport_scrappage_p <- iea_transport %>% 
  filter(grepl(scrappage, Policy, ignore.case = T))

iea_transport_scrappage <- rbind(iea_transport_scrappage_d, iea_transport_scrappage_p) %>% distinct(.keep_all = TRUE)

write_csv(iea_transport_scrappage, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/iea_transport_scrappage.csv")

##############
  
taxation <- c("purchase tax|registration tax|ownership tax|motor tax|bonus-malus scheme|CO2-based|vehicle tax")

iea_transport_taxation_d <- iea_transport %>% 
  filter(grepl(taxation, Description, ignore.case = T))

iea_transport_taxation_p <- iea_transport %>% 
  filter(grepl(taxation, Policy, ignore.case = T))

iea_transport_taxation <- rbind(iea_transport_taxation_d, iea_transport_taxation_p) %>% distinct(.keep_all = TRUE)

write_csv(iea_transport_taxation, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/iea_transport_taxation.csv")

#############

taxation_loose_search <- c("purchase|registration|ownership|motor|bonus-malus")
iea_transport_taxation_loose_search_d <- iea_transport %>% 
  filter(grepl(taxation_loose_search, Description, ignore.case = T))

iea_transport_taxation_loose_search_p <- iea_transport %>% 
  filter(grepl(taxation_loose_search, Policy, ignore.case = T))

iea_transport_taxation_loose_search <- rbind(iea_transport_taxation_loose_search_d, iea_transport_taxation_loose_search_p) %>% distinct(.keep_all = TRUE)

write_csv(iea_transport_taxation_loose_search, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/iea_transport_taxation_loose_search.csv")

```


# Double filter for low carbon financial support
```{r}

instrument_type <- c("VAT|tax credits|tax wavers|direct subsidies|financial aid|financial support") 
iea_transport_instrument_type_d <- iea_transport %>% 
  filter(grepl(instrument_type, Description, ignore.case = T))

iea_transport_instrument_type_p <- iea_transport %>% 
  filter(grepl(instrument_type, Policy, ignore.case = T))

iea_transport_instrument_type <- rbind(iea_transport_instrument_type_d, iea_transport_instrument_type_p) %>% distinct(.keep_all = TRUE)

#write_csv(iea_transport_instrument_type, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/iea_transport_instrument_type.csv")

objective <- c("low-carbon vehicles|EV|electric battery|hybrid vehicles|ethanol|natural gas|hydrogen|van|truck|bicycles|private vehicles|commercial vehicles") # filter by objective of instrument

low_carbon_objective_d <- iea_transport_instrument_type %>% 
  filter(grepl(objective, Description, ignore.case = T))

low_carbon_objective_p <- iea_transport_instrument_type %>% 
  filter(grepl(objective, Policy, ignore.case = T))

low_carbon_objective <- rbind(low_carbon_objective_p, low_carbon_objective_d) %>% distinct(.keep_all = TRUE)

write_csv(low_carbon_objective, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/low_carbon_objective.csv")

```

# Insights - frequency by year

TO DO: REORDER BINS DESCENDING
```{r, fig.width=7, fig.height=7}
labels <- c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022)

lowcarbon_freq <- low_carbon_objective %>% 
  ggplot(aes(x = Year)) + geom_bar() + scale_x_continuous(breaks = labels, labels = labels) + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including financial support for low-carbon vehicles - broad search")

lowcarbon_freq

# ggsave("iea_transport_freq.png", plot = iea_transport_freq, device = "png", width = 10, height = 10)

taxation_freq <- iea_transport_taxation %>% 
  ggplot(aes(x = Year)) + geom_bar() + scale_x_continuous(breaks = labels, labels = labels) + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including CO2-based taxation schemes")

taxation_freq

scrappage_freq <- iea_transport_scrappage %>% 
  ggplot(aes(x = Year)) + geom_bar() + scale_x_continuous(breaks = labels, labels = labels) + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including scrappage schemes")

scrappage_freq

renovation_freq <- iea_building_renovation %>% 
   ggplot(aes(x = Year)) + geom_bar() + scale_x_continuous(breaks = labels, labels = labels) + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including building renovation support")

renovation_freq


```

# Insights - frequency by country 


```{r, , fig.width=7, fig.height=7}
lowcarbon_freq <- low_carbon_objective %>% 
  ggplot(aes(x = country_code)) + geom_bar() + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including financial support for low-carbon vehicles - broad search")

lowcarbon_freq

# ggsave("iea_transport_freq.png", plot = iea_transport_freq, device = "png", width = 10, height = 10)

taxation_freq <- iea_transport_taxation_1 %>% 
  ggplot(aes(x = country_code)) + geom_bar() + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including CO2-based taxation schemes")

taxation_freq

scrappage_freq <- iea_transport_scrappage %>% 
  ggplot(aes(x = country_code)) + geom_bar() + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including scrappage schemes")

scrappage_freq

renovation_freq <- iea_building_renovation %>% 
   ggplot(aes(x = country_code)) + geom_bar() + scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)) + theme_bw() + ggtitle("Number of IEA policies including building renovation support")

renovation_freq

```


## Remove dups

### Low-carbon support for vehicles
```{r}
library(readxl)
low_carbon <- read_excel("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/OECD_missing_policies_final.xlsx", sheet = 1)

library(tidyverse)
library(quanteda)
library(quanteda.textstats)

low_carbon <- low_carbon %>% 
  tibble::rowid_to_column("index") # add index column

corp <- corpus(low_carbon$Policy) # prepare corpus using policy name 
docnames(corp) <- paste(low_carbon$index) # index of policy as docname

dfmat <- corp %>% tokens(remove_punc=TRUE) %>%
  dfm()

sim_mat <- textstat_simil(dfmat, method="cosine")
sim_df <- as.data.frame(sim_mat, upper=TRUE)


sim_filt <- sim_df %>% filter(cosine >= 0.7) # threshold for duplicate

lab_copy <- low_carbon # create a copy 
lab_copy$cos_dup <- NA

for (i in 1:nrow(sim_filt)) {        # remove duplicates with different countries
  index1 = as.numeric(sim_filt[i,1])
  index2 = as.numeric(sim_filt[i,2])
  if(lab_copy[index1,2]!=lab_copy[index2,2]){
    sim_filt[i, 3] = NA
    sim_filt_2 <- na.omit(sim_filt)
    }
}
for (i in 1:nrow(sim_filt_2)){       # labeling 
  index1 = as.numeric(sim_filt_2[i,1])
  lab_copy[index1,9] = paste(lab_copy[index1,9], sim_filt_2[i,2], sep = ",")}

lab_copy$cos_dup <- trimws(lab_copy$cos_dup, whitespace = "NA,")

low_carbon <- lab_copy

write_csv(low_carbon, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/ low_carbon_nodup.csv")

```


### Scrappage schemes
```{r}
library(readxl)
scrappage <- read_excel("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/OECD_missing_policies_final.xlsx", sheet = 2)

library(tidyverse)
library(quanteda)
library(quanteda.textstats)

scrappage <- scrappage %>% 
  tibble::rowid_to_column("index") # add index column

corp <- corpus(scrappage$Policy) # prepare corpus using policy name 
docnames(corp) <- paste(scrappage$index) # index of policy as docname

dfmat <- corp %>% tokens(remove_punc=TRUE) %>%
  dfm()

sim_mat <- textstat_simil(dfmat, method="cosine") # compute cosine similarity
sim_df <- as.data.frame(sim_mat, upper=TRUE) # create df 


sim_filt <- sim_df %>% filter(cosine >= 0.7) # filter df by cosine similarity threshold

lab_copy <- scrappage # create a copy 
lab_copy$cos_dup <- NA # create new col

for (i in 1:nrow(sim_filt)) {        # remove duplicates with different countries
  index1 = as.numeric(sim_filt[i,1])
  index2 = as.numeric(sim_filt[i,2])
  if(lab_copy[index1,2]!=lab_copy[index2,2]){ # if countries are diff, then it's not a dup 
    sim_filt[i, 3] = NA
    sim_filt_2 <- na.omit(sim_filt)
    }
}

for (i in 1:nrow(sim_filt)){       # labeling 
  index1 = as.numeric(sim_filt[i,1])
  lab_copy[index1,9] = paste(lab_copy[index1,9], sim_filt[i,2], sep = ",")}

lab_copy$cos_dup <- trimws(lab_copy$cos_dup, whitespace = "NA,")

scrappage <- lab_copy

write_csv(scrappage, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/ scrappage_nodup.csv")

```

### Taxation
```{r}
library(readxl)
taxation <- read_excel("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/OECD_missing_policies_final.xlsx", sheet = 3)

library(tidyverse)
library(quanteda)
library(quanteda.textstats)

taxation <- taxation %>% 
  tibble::rowid_to_column("index") # add index column

corp <- corpus(taxation$Policy) # prepare corpus using policy name 
docnames(corp) <- paste(taxation$index) # index of policy as docname

dfmat <- corp %>% tokens(remove_punc=TRUE) %>%
  dfm()

sim_mat <- textstat_simil(dfmat, method="cosine")
sim_df <- as.data.frame(sim_mat, upper=TRUE)


sim_filt <- sim_df %>% filter(cosine >= 0.7) # threshold for duplicate

lab_copy <- taxation # create a copy 
lab_copy$cos_dup <- NA

for (i in 1:nrow(sim_filt)) {        # remove duplicates with different countries
  index1 = as.numeric(sim_filt[i,1])
  index2 = as.numeric(sim_filt[i,2])
  if(lab_copy[index1,2]!=lab_copy[index2,2]){
    sim_filt[i, 3] = NA
    sim_filt_2 <- na.omit(sim_filt)
    }
}
for (i in 1:nrow(sim_filt_2)){       # labeling 
  index1 = as.numeric(sim_filt_2[i,1])
  lab_copy[index1,9] = paste(lab_copy[index1,9], sim_filt_2[i,2], sep = ",")}

lab_copy$cos_dup <- trimws(lab_copy$cos_dup, whitespace = "NA,")

taxation <- lab_copy

write_csv(taxation, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/ taxation_nodup.csv")

```


### Building renovation

```{r}
library(readxl)
renovation <- read_excel("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/OECD_missing_policies_final.xlsx", sheet = 4)

library(tidyverse)
library(quanteda)
library(quanteda.textstats)

renovation <- renovation %>% 
  tibble::rowid_to_column("index") # add index column

corp <- corpus(renovation$Policy) # prepare corpus using policy name 
docnames(corp) <- paste(renovation$index) # index of policy as docname

dfmat <- corp %>% tokens(remove_punc=TRUE) %>%
  dfm()

sim_mat <- textstat_simil(dfmat, method="cosine")
sim_df <- as.data.frame(sim_mat, upper=TRUE)


sim_filt <- sim_df %>% filter(cosine >= 0.7) # threshold for duplicate

lab_copy <- renovation # create a copy 
lab_copy$cos_dup <- NA

for (i in 1:nrow(sim_filt)) {        # remove duplicates with different countries
  index1 = as.numeric(sim_filt[i,1])
  index2 = as.numeric(sim_filt[i,2])
  if(lab_copy[index1,2]!=lab_copy[index2,2]){
    sim_filt[i, 3] = NA
    sim_filt_2 <- na.omit(sim_filt)
    }
}
for (i in 1:nrow(sim_filt)){       # labeling 
  index1 = as.numeric(sim_filt[i,1])
  lab_copy[index1,9] = paste(lab_copy[index1,9], sim_filt[i,2], sep = ",")}

lab_copy$cos_dup <- trimws(lab_copy$cos_dup, whitespace = "NA,")

renovation <- lab_copy

write_csv(renovation, "C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/oecd_data_task/ renovation_nodup.csv")

```

