---
title: "ceres_plotting"
author: "Laura Menicacci"
date: "2022-11-30"
output: html_document
---

```{r, echo=FALSE}
library(tidyverse)

ceres <- read_csv("C:/Users/laura/OneDrive/Documenti/LAURA/MCC/futurelab_ceres/ceres_secondversion.csv")
```

```{r, echo=FALSE, warning=FALSE}
countries <- c("Australia", "Austria", "Belgium","Canada","Denmark", "Finland", "France", "Germany", "Greece", "Ireland", "Italy", "Japan", "Luxembourg", "Netherlands","New Zealand", "Portugal",  "Spain", "Sweden", "Switzerland", "United Kingdom", "United States of America")

ceres %>% 
  group_by(country) %>% 
  ggplot(aes(x = indicator_database_source)) + geom_bar(stat = "count", fill = "lightblue", alpha = 0.9) + theme_bw() + xlab("Database source") + labs(title = "Share of policies per database source", subtitle = "Filtered by 21 Annex I countries")
  
```

```{r fig.align="center", echo = FALSE, fig.width = 14, warning=FALSE}
fig <- ceres %>% 
  filter(country %in% countries) %>% 
  group_by(country) %>% 
  ggplot(aes(x = country, fill = indicator_database_source)) + geom_bar(stat = "count", width = 0.8) + theme_bw() + xlab("Countries") + labs(title = "Share of policies per database source by country", subtitle = "Filtered by 21 Annex I countries")

fig 

ggsave("Share of policies per database source by country_byNC.png", plot = fig, device = "png", width = 10, height = 8)

```

```{r fig.align="center", echo = FALSE,  warning=FALSE}
ceres %>% 
  filter(country %in% countries) %>% 
  filter(indicator_database_source %in% c("Climate Policy Database", "EEA")) %>% 
  ggplot(aes(x = year_implementation)) + geom_bar(stat = "count", fill = "lightblue") + theme_bw() + labs(title = "Frequency of implementation Years")

```

```{r  fig.align="center", echo = FALSE, warning=FALSE}
ceres %>% 
  filter(country %in% countries) %>% 
  filter(indicator_database_source %in% c("Climate Policy Database", "EEA")) %>% 
  ggplot(aes(x = year_decision)) + geom_bar(stat = "count", fill = "lightblue") + theme_bw() + labs(title = "Frequency of decision years")

```

```{r fig.align="center", echo = FALSE, warning=FALSE}
ceres %>% 
  filter(country %in% countries) %>% 
  ggplot(aes(x = year)) + geom_bar(stat = "count", fill = "lightblue") + theme_bw() + labs(title = "Frequency of Year - UNFCCC")
```

