---
title: "zero_count"
author: "Laura Menicacci"
date: "2024-04-26"
output: html_document
---
# Count very carefully where we even have zeros and how many they are

```{r, fig.height = 15, fig.width = 15, echo=FALSE}

suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(here)))
suppressWarnings(suppressMessages(library(doParallel)))
suppressWarnings(suppressMessages(library(gdata)))
suppressWarnings(suppressMessages(library(gridExtra)))
suppressWarnings(suppressMessages(library(ggridges)))
suppressWarnings(suppressMessages(library(kableExtra)))


here::i_am("sharing/zeros.Rmd")

# Load plotting functions
#source("C:\\Users\\laura\\OneDrive\\Documenti\\LAURA\\MCC\\futurelab_ceres\\patent_data_project\\code\\plotting_functions.R")

top_main <- c("JPN", "USA", "KOR", "DEU", "CHN", "FRA", "GBR", "CAN", "ITA", "DNK", "NLD", "IND", "AUT", "CHE", "SWE", "ESP", "AUS", "ISR", "BEL", "FIN", "RUS", "NOR", "BRA")

df <- read_csv("C:\\Users\\laura\\OneDrive\\Documenti\\LAURA\\MCC\\futurelab_ceres\\patent_data_project\\data\\patents_panel_5techs.csv", show_col_types = F)  %>% filter(ISO %in% top_main)

df1 <- read_csv("C:\\Users\\laura\\OneDrive\\Documenti\\LAURA\\MCC\\futurelab_ceres\\patent_data_project\\data\\patents_panel_5techs_spread.csv", show_col_types = F)  %>% filter(ISO %in% top_main)

```

## Sample goes from 2000 to 2019 with 23 countries (original top 25 minus Taiwan and Singapore)
```{r, fig.height = 15, fig.width = 15, echo=FALSE}

zeros <- df1 %>%
  filter(year > 1999) %>% 
  group_by(ISO, year) %>% 
  filter(if_any(starts_with("count_"), ~ . == 0)) %>% 
  select(!c(count_ccmt, count_energy)) %>%  # these do not have zeros
  summarize(count_solar_zeros = sum(count_solar == 0),
  count_wind_zeros = sum(count_wind == 0), 
  count_storage_zeros = sum(count_storage == 0), .groups = "keep") %>% 
  pivot_longer(cols = starts_with("count_"), names_to = "Technology", values_to = "Count") %>% 
  ungroup()

zeros %>% 
  ggplot(aes(x = year, y = Count, fill = Technology)) +
  geom_col(position = "stack") +
  facet_wrap(~ISO, scales = "free_y") +
  scale_x_continuous(breaks = seq(2000, 2020, by = 2))+
  #scale_y_continuous(breaks = c(0,1, 2))+
  theme_bw()+
  theme(legend.position = "bottom") + 
  ggtitle("Count of zeros by country and technology", subtitle = "Australia and Japan have no zeros. Ccmt and energy have no zeros.")


```


## Table format 

Number of zero counts by country, in descending order.Over all technologies. 

```{r, echo=FALSE}

zeros %>% 
  group_by(ISO) %>% 
  filter(Count == 1) %>% 
  count(Count) %>% 
  select(ISO, n) %>% 
  arrange(desc(n)) %>% 
  kable(format = "html") #%>% 
#kable_styling(bootstrap_options = c("hover", "responsive"), full_width = F, fixed_thead = T, position = "left") %>% 
#scroll_box(width = "300px", height = "300px")

```


# total number of zeros in our sample
```{r, echo=FALSE}
zeros %>% 
  filter(Count ==1) %>% 
  count(nrow(Count))%>% 
  kable(format = "html") 
```



