---
title: "comparison_results"
author: "Laura Menicacci"
date: "2023-12-13"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

# devtools::install_github("moritzpschwarz/getspanel")
library(tidyverse)
library(gets)
library(getspanel)

## Put all results together (THESE ARE THE OLD RESULTS)

#ccmt_IIS <- readRDS(".\\results\\ccmt_IIS.RDS")
#ccmt_noIIS <- readRDS(".\\results\\ccmt_noIIS.RDS")
#ccmt <- rbind(ccmt_IIS, ccmt_noIIS)
#
#energy_IIS <- readRDS(".\\results\\energy_IIS.RDS")
#energy_noIIS <- readRDS(".\\results\\energy_noIIS.RDS")
#energy <- rbind(energy_IIS, energy_noIIS)
#
#solar_IIS <- readRDS(".\\results\\solar_IIS.RDS")
#solar_noIIS <- readRDS(".\\results\\solar_noIIS.RDS")
#solar <- rbind(solar_IIS, solar_noIIS)
#
#wind_IIS <- readRDS(".\\results\\wind_IIS.RDS")
#wind_noIIS <- readRDS(".\\results\\wind_noIIS.RDS")
#wind <- rbind(wind_IIS, wind_noIIS)
#
#batteries_IIS <- readRDS(".\\results\\batteries_IIS.RDS")
#batteries_noIIS <- readRDS(".\\results\\batteries_noIIS.RDS")
#batteries <- rbind(batteries_IIS, batteries_noIIS)
#
#results <- rbind(ccmt, energy, solar, wind, batteries)

```

## This function assigns a list of all the detected breaks for each model specification

```{r}

find_breaks <- function(results_df) {

  results_df$breaks <- vector("list", length = nrow(results_df))

  for (i  in 1:nrow(results_df)){
  
    for (j in results_df$is[i]) {
      
      for (k in j$isatpanel.result$ISnames) {
          breaks <- get_indicators(j)$fesis$name
          results_df$breaks[i] <- list(breaks)
    }
  }
  
}
 return(results_df)
  } 


# TO DO: MAKE MORE EFFICIENT (remove nested loops)


```

## try a more efficient one (doesn't work)

```{r}

find_breaks2 <- function(results_df) {
  results_df$breaks <- lapply(results_df$is, function(j) {
    lapply(j$isatpanel.result$ISnames, function(k) {
      get_indicators(j)$fesis$name
    })
  })
  return(results_df)
}

## Add breaks

#ccmt <- find_breaks(ccmt) %>% mutate(tech = "ccmt")
# 
#energy <- find_breaks(energy) %>% mutate(tech = "energy")
#
#solar <- find_breaks(solar) %>% mutate(tech = "solar")
#
#wind <- find_breaks(wind) %>% mutate(tech = "wind")
#
#batteries <- find_breaks(batteries) %>% mutate(tech = "batteries")
#
#all_res <- rbind(ccmt, energy, solar, wind, batteries) 
#
#saveRDS(all_res, ".\\all_res_break_comp.RDS")

```


## How to compare across models and samples the breaks? 

```{r}

res_prova <- res_w_breaks %>% select(!is)

res_prova <- res_prova %>% 
  unnest(cols = breaks) %>% # Extract list and make the df longer
  # Transform list in 2 columns: break_year and break_iso
  mutate(break_year = str_sub(breaks, 10, 13), 
         break_ISO = str_sub(breaks, 6, 8)) %>% 
  select(!(breaks)) # remove old columns

res_prova$break_year <- as.numeric(res_prova$break_year)
  
common_breaks <- data.frame() 

for (i in 1:(nrow(res_prova)-1)){
  for (j in (i + 1):nrow(res_prova)){
    # Select only breaks that are of the same country and with a conf int of +-3y 
    if(res_prova$break_ISO[i] == res_prova$break_ISO[j] && abs(res_prova$break_year[i] - res_prova$break_year[j]) <= 3){
      common_breaks <- rbind(common_breaks, res_prova[i, ], res_prova[j, ])
      common_breaks <- common_breaks %>% distinct()
    } 
  }
}


```

## Function that extracts breaks and filters for common breaks across specifications and technologies

```{r}
filter_for_common_breaks <- function(res_with_breaks_list) {

res_with_breaks_list <- res_with_breaks_list %>% 
  unnest(cols = breaks) %>% # Extract list and make the df longer
  # Transform list in 2 columns: break_year and break_iso
  mutate(break_year = str_sub(breaks, 10, 13), 
         break_ISO = str_sub(breaks, 6, 8)) %>% 
  select(!(breaks)) # remove old columns

res_with_breaks_list$break_year <- as.numeric(res_with_breaks_list$break_year)
  
common_breaks <- data.frame() 

for (i in 1:(nrow(res_with_breaks_list)-1)){
  for (j in (i + 1):nrow(res_with_breaks_list)){
    # Select only breaks that are of the same country and with a conf int of +-3y 
    if(res_with_breaks_list$break_ISO[i] == res_with_breaks_list$break_ISO[j] && abs(res_with_breaks_list$break_year[i] - res_with_breaks_list$break_year[j]) <= 3){
      common_breaks <- rbind(common_breaks, res_with_breaks_list[i, ], res_with_breaks_list[j, ])
      common_breaks <- common_breaks %>% distinct()
    } 
  }
}
 return(common_breaks)
  } 

```


# Try if it works
```{r}

prova_comm_br <- filter_for_common_breaks(res_w_breaks)

```

